name: vscode-tunnel
description: GitHub Action to host a VSCode server locally
author: Pavel Zwerschke
branding:
  icon: code
  color: blue
inputs:
  abc:
    description: abc
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Download pixi
      uses: prefix-dev/setup-pixi@v0.8.3
    - name: Temp
      shell: bash
      id: url
      run: echo hello
