[project]
name = "ci-test"
version = "0.1.0"
description = "Add a short description here"
authors = []
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]

[dependencies]
python = "3.12.0.*"
