# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

# source:
#   - url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
#     sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02

package:
  name: ${{ name }}
  version: ${{ version }}
build:
  script:
    - ls -lah
requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
