on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: mxschmitt/action-tmate@v3
      - uses: ./
        with:
          ngrok-token: ${{ secrets.NGROK_TOKEN }}
          vscode-password: ${{ secrets.VSCODE_PASSWORD }}
      # - uses: mxschmitt/action-tmate@v3
