name: run-github-workflows

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-yml-micromamba:
    name: solve .yml file with micromamba
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: setup micromamba and solve environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: ${{ runner.os }}
    - run: which conda
    # - uses: mxschmitt/action-tmate@v3
    - name: export conda environment created using micromamba
      run: |
        micromamba env export --name ${{ runner.os }} | grep -v "^prefix: " > ./environments/${{ runner.os }}_solved.yml
        conda list --explicit > ./environments/csp_${{ runner.os }}_solved.txt
        conda env export -p "${MAMBA_ROOT_PREFIX}/envs/${{ runner.os }}" > ./environments/${{ runner.os }}_solved_with_pip.yml
    - name: add and commit exported conda environment
      uses: stefanzweifel/git-auto-commit-action@v4
