on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, world!"
        shell: ls -lah {0}
      - run: echo $PATH
      - run: ls /usr/local/bin
      - run: ls /usr/local/sbin
      - run: ls /usr/bin
      - run: ls /usr/sbin
      - run: ls /bin
      - run: ls /sbin

  test-win:
    runs-on: windows-latest
    steps:
      - run: |
          echo "Hello, world!"
      - run: echo $PATH
        shell: bash
      - run: echo %PATH%
        shell: cmd
      - run: $Env:Path
        shell: powershell
      - run: $Env:GITHUB_PATH
        shell: powershell
      - run: |
          cd $HOME
          mkdir on-path
          echo "python --version" >> on-path\python-custom
          chmod +x on-path\python-custom
          echo "$HOME/on-path" >> $GITHUB_PATH
      - run: python-custom
        shell: bash
      - run: test
        shell: python-custom
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash
      - run: cat $GITHUB_PATH
        shell: bash
      - uses: mxschmitt/action-tmate@v3
      # - run: ls /usr/local/bin
      # - run: ls /usr/local/sbin
      # - run: ls /usr/bin
      # - run: ls /usr/sbin
      # - run: ls /bin
      # - run: ls /sbin