on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, world!"
        shell: ls -lah {0}
      - run: echo $PATH
      - run: ls /usr/local/bin
      - run: ls /usr/local/sbin
      - run: ls /usr/bin
      - run: ls /usr/sbin
      - run: ls /bin
      - run: ls /sbin

  test-win:
    runs-on: windows-latest
    steps:
      - run: |
          echo "Hello, world!"
      - run: echo $PATH
        shell: bash
      - run: echo %PATH%
        shell: cmd
      - run: ls /usr/local/bin
      - run: ls /usr/local/sbin
      - run: ls /usr/bin
      - run: ls /usr/sbin
      - run: ls /bin
      - run: ls /sbin