name: CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: rattler-build=0.5.2
      - run: rattler-build build -r conda.recipe/recipe.yaml -m conda.recipe/variants-linux-aarch64.yaml --target-platform=linux-aarch64 --no-test
        shell: bash -el {0}
