name: CI

on:
  push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: prefix-dev/setup-pixi@v0.3.0
      - run: |
          tmp="$(mktemp)"
          echo "print('hello world')" > "$tmp"
          pixi run python -c "$tmp"
