on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: cat ~/.bashrc
        shell: bash
      - run: cat ~/.bash_profile
        shell: bash
      - run: |
          printf "\necho bashrc" >> ~/.bashrc
          printf "\necho bash_profile" >> ~/.bash_profile
      - name: Default
        run: echo "Hello World"
      - name: bash -el {0}
        shell: bash -el {0}
        run: echo "Hello World"
      - name: bash -ei {0}
        shell: bash -ei {0}
        run: echo "Hello World"
      - name: bashrc
        run: cat ~/.bashrc
      - name: bash_profile
        run: cat ~/.bash_profile
      - uses: mxschmitt/action-tmate@v3
        if: failure()
