name: CI

on:
  push

jobs:
  no-environment-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: >-
            python>=3.11
            python<3.10
      - run: |
          micromamba info | grep -q "environment : test"
        if: false
        shell: bash -el {0}

  environment-file:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: 'test/environment.yml'
      - run: |
          micromamba info | grep -q "environment : env-name"
        shell: bash -el {0}
