name: windows
on:
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: 'windows-latest'
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          # init-shell: bash
          environment-name: test
          # create-args: python=3.7 pypy pip
      - uses: mxschmitt/action-tmate@v3
