name: windows
on:
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Micromamba
      #   uses: mamba-org/setup-micromamba@v1
      #   with:
      #     # init-shell: bash
      #     environment-name: test
      #     # create-args: python=3.7 pypy pip
      - run: |
          echo hello world
        shell: cat {0}
