on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: Write-Host "Hello World"
        shell: pwsh
      - run: pwsh --version
        shell: bash
      - run: powershell --version
        shell: bash
      - run: Write-Host "Hello World"
        shell: powershell
