name: Test version-metadata

on: [push]

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pavelzw/ui-actions/version-metadata@custom-extractor
        id: version-metadata
        with:
          file: ./version.py
          versionExtractionOverride: 'command:./read_version.sh'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "Version changed: ${{ steps.version-metadata.outputs.changed }}"
      - run: |
          echo "New version: ${{ steps.version-metadata.outputs.newVersion }}"
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quantco/ui-actions/version-metadata@v1
      # - uses: pavelzw/ui-actions/version-metadata@custom-extractor
        id: version-metadata
        with:
          file: ./version.yml
          version-extraction-override: 'regex:version: (.*)'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "Version changed: ${{ steps.version-metadata.outputs.changed }}"
      - run: |
          echo "New version: ${{ steps.version-metadata.outputs.newVersion }}"